app:
  title: Platform Backstage
  baseUrl: http://192.168.0.12:7007

backend:
  baseUrl: http://192.168.0.12:7007
  listen:
    port: 7007
    host: 0.0.0.0
    auth:
      dangerouslyDisableDefaultAuthPolicy: true
    
  cors:
    origin: http://192.168.0.12:7007


  database:
    client: sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

extraEnvVars:
  - name: BACKSTAGE_AUTH_SECRET
    valueFrom:
      secretKeyRef:
        name: backstage-auth-secret
        key: BACKSTAGE_AUTH_SECRET


auth:
  environment: development
  providers: {}