app:
  title: Platform Backstage
  baseUrl: http://localhost:30007

backend:
  baseUrl: http://localhost:30007
  listen:
    port: 7007
    auth:
      dangerouslyDisableDefaultAuthPolicy: true


  database:
    client: sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

extraEnvVars:
  - name: BACKSTAGE_AUTH_SECRET
    valueFrom:
      secretKeyRef:
        name: backstage-auth-secret
        key: BACKSTAGE_AUTH_SECRET


auth:
  environment: development
  providers: {}