apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ appName }}
  description: Kubernetes service {{ appName }}
  tags:
    - kubernetes
    - helm
spec:
  type: service
  lifecycle: experimental
  owner: {{ owner }}
