# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_CLIENT_ID: T3YyM2xpY09ncXp1djNPTWFlN00=
  GITHUB_CLIENT_SECRET: MTJkNThmY2YwOGFmNzUwOTc2N2ZlMjg4MzllZGQwMzQzOWFlMWFlNA==
