apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.production.yaml: |
    app:
      title: Backstage
      baseUrl: http://backstage.local

    backend:
      baseUrl: http://backstage.local
      listen:
        port: 7007

    database:
      client: pg
      connection:
        host: postgres.backstage.svc.cluster.local
        port: 5432
        user: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        database: backstage
