---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgBYpGd3cVGiY/Cw6EBESoD9EbuOJZJbNaqDjo4vR3U4SCukDyuxnl8fSV9bO6ojyTEoRMSj16iYQWrN78iitpio2sE6E+KBGW0Xt2h3/8189LMXYNzYdvPeHdBzAS6YrAfFN4WdtFQInuN1yUXI9HDGwDdI44F/qaWirjugY02fOtHHj6POJU9YN5ZD3e8L1ayyeWzpnGkUCvAYS+/bpBCoUZuv3cpOMOPtJDGfKVM6V25fd3mJdwTfQH/DKshcrAMc6Aql+VLpfmcFVLUNMFVXdeipwxrjAovh0IAvYzct2xrbysaUtUYTu6aktmfok+DTsDPYiaUpggfuCN3FlFNgYfYz8DDeVytiMdePtdJ6LdWTN7H17aaTHW8MMBRshjuyKBI5WuAiJ5j3AU2voVvmoK8/frnh4g1NRweS7HZCfd+wIW84CGvb6AHyoFu9CVyLsPtx8qC7CrmJ/tzos0mwDgKkVcvIJP5v4OzOVV/t4hYginHwwyXnnOd54Slu3Q8VuUwdEb9pBV1ClhVOYxVYTsE0MSj8y+mpf15ZAYo95pGpgDxFDKMEsrKmJ8PSHnlCK1lqpMWViO+HxzACWbBOUxHyaH0HrZQRhWjLbiTZ6ZJ2/Q9Hw7s4xYs/7tYeRgi77J6GJ1ly5E838tezAUIExSsz8lwPHtyxcM0TZkH4DUwEs+zF3AoJDbnCkhXqXI3+zUskHAkY2Jo7SU0+CAVhL3hQdLsIl2YhaDy+
    GITHUB_CLIENT_SECRET: AgCwUVEv2R0I+PVBOPc3AmSbw5JMSVxb0QZwgKiLxukn4GJDUPguIdMMyPcXSYHvDL0e83lTRnLGeYoNnd96TOqA2LGRaUYKdNqAnAloZbtFT6+eXpb0wlSla+jYWX0sU9RExRZFhcC2M3t+Gk8Iatt+1R7kDU7RLzuQXjBpbmLLZREQM8C5jCDKL4X4rDhAnBxEp4XQ1t2rI9yNVEAFnAj9M6LHHc+rKb1IYbiqJ0uWzdfQGc5xM053TgimXqDRlT7ZhKc/V0lQ1LeJmV7WThtbk+vXyeQNDfBc4UafS/0qjO+PPThfD+v0Q5KFhsgdrs84FsC8XZzO1jVa3AjX1NOCrBfCjJlXJyAj2UogQhbstt+k56cv4TRaUtAi8xvQtSp7lYlT7+e6D1xyY1KUPJQ6pK/NOuWIK9XCOS+AhW0Nu3MFAx84OIeB1+kMSgHU31ORzYWEMCcJUxyiWw7ivqerC3N4frC4D196U/DtxBp/xcfvmt/lAk9jMIWDQ+fc7s9o57RFNFEMfzDGMQ6gIfTVCHjT5py9NliNdlan6tcEZeHQ/JP/EmVv38UwrlHaXV4KOVeE2FdenT64/Osfrs5lUXqQuG4Ednm4CeYE/gHk1mt/nJ7IqP/CN2b6ld69vdns6r+/CN65clIDtcvo3B5bIkBVpAv1uqZekNiYgONVmLvICTvg1So9W/LEwEYbeGHv+CJPu0SuvL2fd0dwAqnVHfR3gDW8p20ZcXi3YBHHPSLMpwF0qQOGMHm1M+nyvmFwr5l1aHby0w==
  template:
    metadata:
      name: backstage-secrets
      namespace: backstage
