---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgACLk+ZD4NrZMYTaGZ1ZINPC7uXSfvM+9GOQXva2KgSyqn//hwwDZfQmRnG/oPgGhcF+QcBdUAUtTvtTFKSnCLJzMC/xvznlkccxL2V/sxYED294v1eZzTK9Lx/aljO0TZT+0kUXAMom7o3sHCxIqmTXWTbGKCXtSXE2zpefrjfJvTr8ke2FIeOv0ukotiFVmy42jk5Q2cq/beJx4rQ0Lw44gjSM3e3GtA599dbpeXFeT3b3MfzY3CqDJJDLmJIZ+G+4u1SYEmwIiUZsiB1GGA0QnXtK1Srd6uo1E26m3u0uH0DHmOjMPGZSq92xMHetMrrgUo41c/rqoFEzQJ2CpYyhmdyKE6wO6sYrr7hWPxn7zHaw5R3iqB70bOCTD3sURUMRBK2xVnV0MGQWzhiYYFgnomJocb58Anhe+9BuQQK6zTT8enx5rMTjWxJRL4MgGy3FMgChjsdJxWifg7DeFzCVW9I96CKcIFITZAmsM7zccWH2amzMwUiVj7hzBByLz58D/kTBhNyC77r4bbfxLozUbnolXcMEhEW9OQNiuKscV6QDugEetvaU4fy5fYJedKrLmfrwlpuwlNs3ajJTg/CNqHNUQwxgA0jgdZQapc+L30o6UsLbxzJW+kzgTR4jQHGqxt1pU0EQ9RfNXKlmORMU7YD6xleIfLE8OdCJ89NBIb5ljhdflUyQGBmNwbq+JD/65rvF3i9IDKXJg6QayMUKYdkgg==
    GITHUB_CLIENT_SECRET: AgBoawwpS0zNTcFNUHYdmvBB3GSTBcnh6vDbLklSKDmQZ2WnalK8ohDm6dU/eB0Zw/wK7l6+2/x7UyGPKcoxUDAUjY/X6M213z3xTUlD/EHHtR6UCuK+U+3zuhbJZu8ISm/i/+RTNDaL40LbgfUMrBOCIVSn913idwoQ5IRj1EZdgXCneNF/tcR4nFyBmzrr6srUehl+tvfegVtSoBPLqIXPgoXcUClPxpo5AbVUXShmXn34DzUCBkPZbU9PVKBQ3F0KQfD8zb8WtPw0OJEwP50alDjbmbfbfFH4awfXELthQ6ZO75o5kS37EE7kWFPI6pQcmk1ygGhYdwuWe4n3zUMvE/JHTq0lT36Ps+VE4VeWvW7xjkpiU6iTtMGzIOx5EuIZ+GDwi7hs6iozyD+V95MYsqnukn9sQvDgXfVsd8LxTnCqkQUDAj7pQbweqXTw0RDnaxosPaIo0r7d7hhAkNKuzYeHT0Yf8bhxX6KMlMWdbhTBnt1ISeMSItnBmOnMY8HkwpdEs8LqIejuZUi1UlwdZU7C606lsEgvaH5DS0cqBXlai+RRSzsRBanFjy50eHFKBmd6g6pfY06Id2i5VXGolCNm4nhhPXdafmZ3m8J/NCYsTxKWAiJSn4CvwRKTNTcfYwpqp3uPeIKcQrtB85wJ37Z67BRYBnWTNZB4O9ssMaY5sxME3coQLIat9nPRgpRY/PM6LtVdU+RWMdfMfUjxS6o7qPU0PzsMQ2Ol13XXSMso3ELZWZRJ
  template:
    metadata:
      name: backstage-secrets
      namespace: backstage
