---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: backstage
spec:
  encryptedData:
    GITHUB_CLIENT_ID: AgAh/WRBh1HoypN1BY2boeDnaYGdfjuJEgUkJfzwiUeo8xG69r4kmF34qMGjiIgXyMYh4TT4BmwnlQYU5QjE3rkR+UA2aZF3bGn2VUB+Oz7XU1DtliVwp0lgQ76CwvoAdFY/HjQZc2yDcafcoOzlnLumhG3mr3rsU7fMb6AvJDs2uoXseorg72cW7HofBfDP8W1aigKuwbt6dMOppxjEGWTUTht/+lXfoHoUpgaw+9xbtKZHnDZcFhOxQ49KIO9lxq84qJxNfkeF7WYbSmJqMi8J9/e2A65V0cSg1o7q+E8HnDK6/0aFTDR14BtjipQdpn1Ot9u6jXHqO2mgwY/W+ecMTFS820xgNHrjZR7q0xoBp+Vxv3IzbUdomaMAyDwEVroMNnejEQpWRJIrW6o4OM++P+bmrPdyg4ekhNsph5EPTm2uwo9LNG9SZiWTTKZbg/A1yBZ21sU5eX2fYYcnm7DwfPicnBvXvofdiI9K67uDCCEYGNiq/ydmuMNXge89dPLeU3tNV3ayA6y0ZVy3vsO7FCdjhyqkCmTUDjIrivSoTIMlcvsa78ahv7B1Xtkv4GSStdF92qz0RkXqJ4uQrTspYySDLbzhUE/W97cEdDF/4KAcF7EACYr54a/wr/XFIAoHHkcXR1Z1tRxFYhfdSv6pam5hSeRDCtcJeU12GkLB37EgeA1DuRL2Ctr6t1pjK1mwQRKrN+gg2pWfs+ZLvIfBnc54cA==
    GITHUB_CLIENT_SECRET: AgA1Sg+JltSHG+YGKLgdb5kAUANxpRzc5Dv6Ew6V0RInctAZzHShNtkKJ//uxzFI4KjKFcY8XNqqmSwnl9Xqa5Om/vStzXK/Y2t3cJlhGBhDkvaesMyebUktBkR1mdM9YZ98E/5ZobkLWsNd3Wii0SbNcMbXd+bW3dfQVK3atJ6AKrn0zC6pDwB7zad73QZjTT6dzNwtGwVQ6RtuxhQvumcIyUzFZixPotK2FdLajUQWhvZWGVfrN/QntOLWFu4cFY/+twCdSSAJEw3TVA68E97RWKg4RRL9YkwNu6hjCc1ukpvbudjU5+sSgHTNcR8DsBPvKtdvX9jYSBD26BueXIE4Nd3rtuXu/3kx9m069Xo+EpahopnLEA6/otWDbKJveQAcOxHSEK4TxiM9qtKvaj3HNiXbWuW3p10pdWb+UmH4r548Aj0H+l9j6K5M42gnl4KAQMSSmZ62ikzYHAifiaSZJt/K+pgerL9ar7aVQAcnpPVgk7lqFtb446w7Fxcf0hPV+UXYNQxSn25y0omgKoe0bzY83SaPhrLMH78mCaOvGj0XZN0rjGc7BLXH0L43jcqiqxOUE26MUDg30fwmsCW3iLLI9gfIu1NIUAHsWuVMww7KFJVq/KjuhKFhO6yLuwa55yO9RRpYtY0z+nqkquIlb9lwlRBP5jEKjPyxEpIZaY/nlSGUzHrxZP8JA+CmFqUXH2+sNBGCdEHuSOr8YoJ5U6IOktKg2pUrZ7eB+/2AC5GHb5Sx7/0l
  template:
    metadata:
      name: backstage-secrets
      namespace: backstage
