apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: app-k8s-helm
  title: Kubernetes App (Helm + ArgoCD)
  description: Create app using helm and argo
spec:
  owner: platform-team
  type: service

  parameters:
    - title: Application Info
      required:
        - name
        - owner
        - port
      properties:
        name:
          title: App name
          type: string
          description: App name (kebab-case)
        owner:
          title: Owner
          type: string
        port:
          title: Application port
          type: number
          default: 80

  steps:
    - id: fetch-base
      name: Fetch template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          appName: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          port: ${{ parameters.port }}

    - id: publish
      name: Publish repository
      action: publish:github
      input:
        repoUrl: github.com?owner=ORG&repo=${{ parameters.name }}
        description: Service ${{ parameters.name }}
        defaultBranch: main

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml
